"""change status_invite type 3

Revision ID: 127f3a225bb5
Revises: 89e6570293c2
Create Date: 2023-08-20 14:39:33.011055

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = '127f3a225bb5'
down_revision = '89e6570293c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
