"""Change user fields sent_invitations,  received_invitations two vesion

Revision ID: 27b85b7929ef
Revises: a4fc5941465c
Create Date: 2023-08-17 00:02:11.749895

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = '27b85b7929ef'
down_revision = 'a4fc5941465c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
