"""Change user fields sent_invitations,  received_invitations 3 vesion

Revision ID: 4436a31ae007
Revises: 27b85b7929ef
Create Date: 2023-08-17 00:08:34.804479

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = '4436a31ae007'
down_revision = '27b85b7929ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
