"""change invite and requedst to action

Revision ID: 598509931f54
Revises: fff2044ed8dd
Create Date: 2023-08-20 23:24:40.232087

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '598509931f54'
down_revision = 'fff2044ed8dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_action', sa.Enum('INVITE', 'JOIN_REQUEST', name='typeaction'), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('status_action', sa.Enum('SENT', 'ACCEPTED', 'REJECTED', name='statusactionwithsent'), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    op.drop_index('ix_invitations_id', table_name='invitations')
    op.drop_table('invitations')
    op.drop_index('ix_join_requests_id', table_name='join_requests')
    op.drop_table('join_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_request', postgresql.ENUM('SENT', 'ACCEPTED', 'DECLINED', name='statusrequest'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='join_requests_company_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='join_requests_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='join_requests_pkey')
    )
    op.create_index('ix_join_requests_id', 'join_requests', ['id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status_invite', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name='invitations_company_id_fkey'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='invitations_recipient_id_fkey'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='invitations_sender_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='invitations_pkey')
    )
    op.create_index('ix_invitations_id', 'invitations', ['id'], unique=False)
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
