"""change name coloumn is_active

Revision ID: 67bf796321aa
Revises: e2eb242855e4
Create Date: 2023-07-27 22:15:01.187553

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = '67bf796321aa'
down_revision = 'e2eb242855e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'privilege')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privilege', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
