"""change status for user default value

Revision ID: 7050feae4aaa
Revises: e109265ff840
Create Date: 2023-07-27 15:21:01.743114

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = '7050feae4aaa'
down_revision = 'e109265ff840'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
