"""Change user fields sent_invitations,  received_invitations 5 vesion

Revision ID: 7b5f42042f43
Revises: d6085476d2df
Create Date: 2023-08-17 00:22:27.997764

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = '7b5f42042f43'
down_revision = '0140f6b7fcb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(length=50), nullable=True))
    op.drop_column('users', 'status_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_user', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
