"""change status_invite type two

Revision ID: 89e6570293c2
Revises: b9267d4b1e0e
Create Date: 2023-08-20 14:11:01.099894

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = '89e6570293c2'
down_revision = 'b9267d4b1e0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('status_invite', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'status_invite')
    # ### end Alembic commands ###
