"""change status_invite type 7

Revision ID: a1ebbd88bc07
Revises: ce27902f5c63
Create Date: 2023-08-20 21:24:59.479948

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'a1ebbd88bc07'
down_revision = 'ce27902f5c63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
