"""Change user fields sent_invitations,  received_invitations

Revision ID: a4fc5941465c
Revises: 0140f6b7fcb7
Create Date: 2023-08-16 23:58:27.513250

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'a4fc5941465c'
down_revision = '0140f6b7fcb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
