"""add updated field to action

Revision ID: a782d0615842
Revises: 598509931f54
Create Date: 2023-08-21 00:12:14.422552

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'a782d0615842'
down_revision = '598509931f54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'updated')
    # ### end Alembic commands ###
