"""change status_invite type 5

Revision ID: acd43ebeca65
Revises: d892beb42354
Create Date: 2023-08-20 17:19:24.152145

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'acd43ebeca65'
down_revision = 'd892beb42354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
