"""change status_invite type

Revision ID: b9267d4b1e0e
Revises: b9b96e15217c
Create Date: 2023-08-20 14:10:18.138896

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9267d4b1e0e'
down_revision = 'b9b96e15217c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'status_invite')
    op.drop_index('ix_join_requests_status_request', table_name='join_requests')
    op.drop_column('join_requests', 'status_request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('status_request', postgresql.ENUM('SENT', 'ACCEPTED', 'DECLINED', name='statusrequest'), autoincrement=False, nullable=True))
    op.create_index('ix_join_requests_status_request', 'join_requests', ['status_request'], unique=False)
    op.add_column('invitations', sa.Column('status_invite', postgresql.ENUM('SENT', 'ACCEPTED', 'DECLINED', name='statusinvite'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
