"""change status_invite type

Revision ID: b9b96e15217c
Revises: 7b5f42042f43
Create Date: 2023-08-20 12:31:17.410334

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'b9b96e15217c'
down_revision = '7b5f42042f43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invitations_status_invite', table_name='invitations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_invitations_status_invite', 'invitations', ['status_invite'], unique=False)
    # ### end Alembic commands ###
