"""Add visible to comapnies

Revision ID: be3e4c167d7e
Revises: 516e40cab7e7
Create Date: 2023-08-10 18:56:39.401242

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'be3e4c167d7e'
down_revision = '516e40cab7e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'visible')
    # ### end Alembic commands ###
