"""change status_invite type 6

Revision ID: ce27902f5c63
Revises: acd43ebeca65
Create Date: 2023-08-20 17:38:40.344938

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'ce27902f5c63'
down_revision = 'acd43ebeca65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
