"""Change user fields sent_invitations,  received_invitations 4 vesion

Revision ID: d6085476d2df
Revises: 4436a31ae007
Create Date: 2023-08-17 00:12:55.559480

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'd6085476d2df'
down_revision = '4436a31ae007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
