"""change status_invite type 4

Revision ID: d892beb42354
Revises: 127f3a225bb5
Create Date: 2023-08-20 15:03:09.747297

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'd892beb42354'
down_revision = '127f3a225bb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
