"""add cascade deleting to questions and answers

Revision ID: e6f7aa9ace9d
Revises: f86393c76f3a
Create Date: 2023-09-05 21:26:38.778161

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'e6f7aa9ace9d'
down_revision = 'f86393c76f3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
