"""change status_request

Revision ID: fff2044ed8dd
Revises: a1ebbd88bc07
Create Date: 2023-08-20 21:50:34.987198

"""
from alembic import op
import sqlalchemy as sa
from db.connect import Base


# revision identifiers, used by Alembic.
revision = 'fff2044ed8dd'
down_revision = 'a1ebbd88bc07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_requests', sa.Column('status_request', sa.Enum('SENT', 'ACCEPTED', 'REJECTED', name='statusrequest'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('join_requests', 'status_request')
    # ### end Alembic commands ###
